# Generated by Django 4.2.5 on 2023-09-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
