# Generated by Django 4.2.5 on 2023-10-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
    ]
