# Generated by Django 4.2.5 on 2023-10-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_product_product_image1_product_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
    ]
